document.querySelectorAll('[data-avatar]').forEach(img=>img.src=window.MAX_AVATAR);
const $=s=>document.querySelector(s),canvas=$('#canvas'),ctx=canvas.getContext('2d');
const avatar=window.MAX_AVATAR,dog=new Image();dog.src=avatar;
const GOOD=[{e:'🦴',p:1,label:'+1 TREAT'},{e:'🎾',p:2,label:'+2 BALL'},{e:'❤️',p:3,label:'+3 LOVE'},{e:'🦴',p:6,label:'+6 GOLDEN BONE',gold:true}];
const BAD=[{e:'🗑️',label:'NOT A TREAT!'},{e:'💧',label:'MUDDY PAWS!'},{e:'🚒',label:'BONK!'}];
let W=0,H=0,running=false,score=0,timeLeft=35,lives=3,golden=0,playerX=.5,items=[],floaters=[],particles=[],last=0,spawnTimer=0,comboCount=0,comboUntil=0,multiplier=1,audioOn=true,audioCtx,musicTimer,guideTimer;
try{audioOn=localStorage.getItem('petGameSound')!=='off'}catch(_){}
const scoreNode=$('#score'),timeNode=$('#time'),livesNode=$('#lives'),goldNode=$('#gold'),goalFill=$('#goalFill'),quickGuide=$('#quickGuide'),combo=$('#combo');
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);ctx.setTransform(d,0,0,d,0,0);W=r.width;H=r.height}
addEventListener('resize',resize);
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('show'));$(id).classList.add('show')}
function setSound(v){audioOn=v;$('#startSound').textContent=$('#gameSound').textContent=v?'🔊':'🔇';try{localStorage.setItem('petGameSound',v?'on':'off')}catch(_){}if(!v)stopMusic()}
function tone(freq=620,d=.06,type='sine',vol=.07){if(!audioOn)return;audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}
function startMusic(){if(!audioOn)return;stopMusic();let i=0,notes=[262,330,392,330,294,349,440,349];musicTimer=setInterval(()=>tone(notes[i++%notes.length],.18,'triangle',.018),360)}function stopMusic(){clearInterval(musicTimer)}
function updateHud(){scoreNode.textContent=score;timeNode.textContent=Math.max(0,Math.ceil(timeLeft));livesNode.textContent=lives;goldNode.textContent=golden;goalFill.style.width=Math.min(100,golden/3*100)+'%'}
function reset(){score=0;timeLeft=35;lives=3;golden=0;playerX=.5;items=[];floaters=[];particles=[];comboCount=0;multiplier=1;updateHud()}
function start(){reset();show('#game');resize();running=true;last=performance.now();spawnTimer=.25;quickGuide.classList.add('on');clearTimeout(guideTimer);guideTimer=setTimeout(()=>quickGuide.classList.remove('on'),2100);startMusic();requestAnimationFrame(loop)}
function addItem(){const bad=Math.random()<.25,src=bad?BAD[Math.floor(Math.random()*BAD.length)]:GOOD[Math.floor(Math.random()*GOOD.length)];items.push({x:34+Math.random()*(W-68),y:-50,size:bad?48:44,speed:135+Math.random()*70,bad,src,rot:(Math.random()-.5)*.35})}
function pop(x,y,text,kind='good'){floaters.push({x,y,text,kind,age:0,life:kind==='gold'?.75:.62,vy:kind==='bad'?-42:-58,drift:(Math.random()-.5)*20})}
function burst(x,y,color,count=12){for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*170,vy:-40-Math.random()*130,age:0,life:.55+Math.random()*.25,size:2+Math.random()*3,color})}
function collision(it,now){if(it.bad){lives--;pop(it.x,it.y,it.src.label,'bad');burst(it.x,it.y,'#ff6673',15);tone(165,.13,'sawtooth',.07);comboCount=0;multiplier=1;combo.classList.remove('on')}else{comboCount++;if(comboCount>=6){multiplier=2;comboUntil=now+3000;combo.classList.add('on')}const earned=it.src.p*multiplier;score+=earned;if(it.src.gold)golden++;pop(it.x,it.y,multiplier>1?it.src.label+' ×2':it.src.label,it.src.gold?'gold':multiplier>1?'combo':'good');burst(it.x,it.y,it.src.gold?'#ffd54a':'#fff',it.src.gold?22:11);tone(it.src.gold?940:720,it.src.gold?.15:.06,'sine',.06)}updateHud()}
function end(){running=false;stopMusic();combo.classList.remove('on');$('#final').textContent=$('#finalStat').textContent=score;let best=0;try{best=Math.max(score,Number(localStorage.getItem('petGameBest')||0));localStorage.setItem('petGameBest',best)}catch(_){best=score}$('#best').textContent=best;show('#result');confetti();tone(523,.12,'triangle',.05);setTimeout(()=>tone(659,.12,'triangle',.05),130);setTimeout(()=>tone(784,.2,'triangle',.05),260)}
function loop(now){if(!running)return;const dt=Math.min(.034,(now-last)/1000);last=now;spawnTimer-=dt;if(spawnTimer<=0){addItem();spawnTimer=.44+Math.random()*.3}timeLeft-=dt;if(multiplier>1&&now>comboUntil){multiplier=1;comboCount=0;combo.classList.remove('on')}if(timeLeft<=0||lives<=0){end();return}const py=H-104;for(let i=items.length-1;i>=0;i--){const it=items[i];it.y+=it.speed*dt;it.rot+=dt*.45;if(it.y>H+70){items.splice(i,1);continue}if(Math.hypot(it.x-playerX*W,it.y-py)<53){collision(it,now);items.splice(i,1)}}for(let i=floaters.length-1;i>=0;i--){const f=floaters[i];f.age+=dt;f.y+=f.vy*dt;f.x+=f.drift*dt;if(f.age>=f.life)floaters.splice(i,1)}for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.age+=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=390*dt;if(p.age>=p.life)particles.splice(i,1)}updateHud();draw();requestAnimationFrame(loop)}
function draw(){ctx.clearRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#8edcff');g.addColorStop(.58,'#dff8c9');g.addColorStop(1,'#73d173');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#ffffff9a';for(let i=0;i<5;i++){ctx.beginPath();ctx.arc((i*113+40)%W,155+i*105,28,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#e8c68d';ctx.beginPath();ctx.moveTo(W*.42,H);ctx.lineTo(W*.5,H*.42);ctx.lineTo(W*.68,H);ctx.fill();ctx.textAlign='center';ctx.textBaseline='middle';for(const it of items){ctx.save();ctx.translate(it.x,it.y);ctx.rotate(it.rot);if(it.bad){ctx.strokeStyle='#ff5c65';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,it.size*.55,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#ff5c65';ctx.beginPath();ctx.moveTo(it.size*.30,-it.size*.52);ctx.lineTo(it.size*.12,-it.size*.18);ctx.lineTo(it.size*.48,-it.size*.18);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.font='900 15px system-ui';ctx.fillText('!',it.size*.30,-it.size*.29)}ctx.font=it.size+'px system-ui';ctx.fillText(it.src.e,0,0);ctx.restore()}for(const p of particles){ctx.globalAlpha=1-p.age/p.life;ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;for(const f of floaters){ctx.globalAlpha=1-f.age/f.life;ctx.font=`900 ${f.kind==='gold'?18:16}px system-ui`;ctx.lineWidth=3;ctx.strokeStyle=f.kind==='bad'?'#ad3245':f.kind==='gold'?'#9b6816':'#302b49';ctx.strokeText(f.text,f.x,f.y);ctx.fillStyle=f.kind==='bad'?'#fff0f2':f.kind==='gold'?'#fff4b9':'#fff';ctx.fillText(f.text,f.x,f.y)}ctx.globalAlpha=1;const size=Math.min(96,W*.22),cx=playerX*W,cy=H-103;ctx.save();ctx.beginPath();ctx.arc(cx,cy,size/2,0,Math.PI*2);ctx.clip();if(dog.complete&&dog.naturalWidth)ctx.drawImage(dog,0,0,dog.naturalWidth,dog.naturalHeight,cx-size/2,cy-size/2,size,size);ctx.restore();ctx.strokeStyle='#fff';ctx.lineWidth=4;ctx.beginPath();ctx.arc(cx,cy,size/2,0,Math.PI*2);ctx.stroke()}
function move(e){if(!running)return;const r=canvas.getBoundingClientRect(),x=(e.touches?e.touches[0].clientX:e.clientX)-r.left;playerX=Math.max(.11,Math.min(.89,x/r.width))}
function confetti(){const box=$('#confetti');box.innerHTML='';const colors=['#ff7658','#ffd451','#6bcf7c','#6e7cff','#df75e8'];for(let i=0;i<36;i++){const n=document.createElement('i');n.style.left=Math.random()*100+'%';n.style.background=colors[i%colors.length];n.style.animationDelay=Math.random()*.6+'s';box.appendChild(n)}}
canvas.addEventListener('pointermove',move);canvas.addEventListener('touchmove',e=>{e.preventDefault();move(e)},{passive:false});addEventListener('keydown',e=>{if(!running)return;if(e.key==='ArrowLeft')playerX=Math.max(.11,playerX-.07);if(e.key==='ArrowRight')playerX=Math.min(.89,playerX+.07)});
$('#play').onclick=start;$('#again').onclick=start;$('#startSound').onclick=$('#gameSound').onclick=()=>setSound(!audioOn);$('#exitGame').onclick=()=>{running=false;stopMusic();show('#start')};$('#share').onclick=async()=>{const data={title:"Max's Sunny Treat Dash",text:'Play Max’s personalized pet game!',url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);$('#share').textContent='LINK COPIED';setTimeout(()=>$('#share').textContent="SHARE MAX'S GAME",1300)}}catch(_){}};
setSound(audioOn);resize();
